// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_application_user

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ApplicationUserDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the user was created in RFC 3339 format\n",
				MarkdownDescription: "timestamp when the user was created in RFC 3339 format\n",
			},
			"email": schema.StringAttribute{
				Computed:            true,
				Description:         "user email\n",
				MarkdownDescription: "user email\n",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "a resource identifier\n",
				MarkdownDescription: "a resource identifier\n",
			},
			"identity_provider": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "name of the identity provider (e.g. Google)\n",
						MarkdownDescription: "name of the identity provider (e.g. Google)\n",
					},
					"url": schema.StringAttribute{
						Computed:            true,
						Description:         "URL of the identity provider (e.g. https://accounts.google.com)\n",
						MarkdownDescription: "URL of the identity provider (e.g. https://accounts.google.com)\n",
					},
				},
				CustomType: IdentityProviderType{
					ObjectType: types.ObjectType{
						AttrTypes: IdentityProviderValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"last_active": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the user was last active in RFC 3339 format\n",
				MarkdownDescription: "timestamp when the user was last active in RFC 3339 format\n",
			},
			"last_login": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the user last signed-in in RFC 3339 format\n",
				MarkdownDescription: "timestamp when the user last signed-in in RFC 3339 format\n",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "user common name\n",
				MarkdownDescription: "user common name\n",
			},
			"provider_user_id": schema.StringAttribute{
				Computed:            true,
				Description:         "unique user identifier\n",
				MarkdownDescription: "unique user identifier\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI of the application user API resource\n",
				MarkdownDescription: "URI of the application user API resource\n",
			},
			"username": schema.StringAttribute{
				Computed:            true,
				Description:         "user username\n",
				MarkdownDescription: "user username\n",
			},
		},
	}
}

type ApplicationUserModel struct {
	CreatedAt        types.String          `tfsdk:"created_at"`
	Email            types.String          `tfsdk:"email"`
	Id               types.String          `tfsdk:"id"`
	IdentityProvider IdentityProviderValue `tfsdk:"identity_provider"`
	LastActive       types.String          `tfsdk:"last_active"`
	LastLogin        types.String          `tfsdk:"last_login"`
	Name             types.String          `tfsdk:"name"`
	ProviderUserId   types.String          `tfsdk:"provider_user_id"`
	Uri              types.String          `tfsdk:"uri"`
	Username         types.String          `tfsdk:"username"`
}

var _ basetypes.ObjectTypable = IdentityProviderType{}

type IdentityProviderType struct {
	basetypes.ObjectType
}

func (t IdentityProviderType) Equal(o attr.Type) bool {
	other, ok := o.(IdentityProviderType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t IdentityProviderType) String() string {
	return "IdentityProviderType"
}

func (t IdentityProviderType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return nil, diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return IdentityProviderValue{
		Name:  nameVal,
		Url:   urlVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewIdentityProviderValueNull() IdentityProviderValue {
	return IdentityProviderValue{
		state: attr.ValueStateNull,
	}
}

func NewIdentityProviderValueUnknown() IdentityProviderValue {
	return IdentityProviderValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIdentityProviderValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (IdentityProviderValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing IdentityProviderValue Attribute Value",
				"While creating a IdentityProviderValue value, a missing attribute value was detected. "+
					"A IdentityProviderValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IdentityProviderValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid IdentityProviderValue Attribute Type",
				"While creating a IdentityProviderValue value, an invalid attribute value was detected. "+
					"A IdentityProviderValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IdentityProviderValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("IdentityProviderValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra IdentityProviderValue Attribute Value",
				"While creating a IdentityProviderValue value, an extra attribute value was detected. "+
					"A IdentityProviderValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra IdentityProviderValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIdentityProviderValueUnknown(), diags
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewIdentityProviderValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return NewIdentityProviderValueUnknown(), diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	if diags.HasError() {
		return NewIdentityProviderValueUnknown(), diags
	}

	return IdentityProviderValue{
		Name:  nameVal,
		Url:   urlVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewIdentityProviderValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) IdentityProviderValue {
	object, diags := NewIdentityProviderValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIdentityProviderValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t IdentityProviderType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIdentityProviderValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIdentityProviderValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIdentityProviderValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIdentityProviderValueMust(IdentityProviderValue{}.AttributeTypes(ctx), attributes), nil
}

func (t IdentityProviderType) ValueType(ctx context.Context) attr.Value {
	return IdentityProviderValue{}
}

var _ basetypes.ObjectValuable = IdentityProviderValue{}

type IdentityProviderValue struct {
	Name  basetypes.StringValue `tfsdk:"name"`
	Url   basetypes.StringValue `tfsdk:"url"`
	state attr.ValueState
}

func (v IdentityProviderValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["url"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Url.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["url"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v IdentityProviderValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v IdentityProviderValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v IdentityProviderValue) String() string {
	return "IdentityProviderValue"
}

func (v IdentityProviderValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"name": basetypes.StringType{},
		"url":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"name": v.Name,
			"url":  v.Url,
		})

	return objVal, diags
}

func (v IdentityProviderValue) Equal(o attr.Value) bool {
	other, ok := o.(IdentityProviderValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Url.Equal(other.Url) {
		return false
	}

	return true
}

func (v IdentityProviderValue) Type(ctx context.Context) attr.Type {
	return IdentityProviderType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v IdentityProviderValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"name": basetypes.StringType{},
		"url":  basetypes.StringType{},
	}
}
