// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_reserved_domain

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ReservedDomainDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"acme_challenge_cname_target": schema.StringAttribute{
				Computed:            true,
				Description:         "DNS CNAME target for the host _acme-challenge.example.com, where example.com is your reserved domain name. This is required to issue certificates for wildcard, non-ngrok reserved domains. Must be null for non-wildcard domains and ngrok subdomains.\n",
				MarkdownDescription: "DNS CNAME target for the host _acme-challenge.example.com, where example.com is your reserved domain name. This is required to issue certificates for wildcard, non-ngrok reserved domains. Must be null for non-wildcard domains and ngrok subdomains.\n",
			},
			"certificate": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "a resource identifier\n",
						MarkdownDescription: "a resource identifier\n",
					},
					"uri": schema.StringAttribute{
						Computed:            true,
						Description:         "a uri for locating a resource\n",
						MarkdownDescription: "a uri for locating a resource\n",
					},
				},
				CustomType: CertificateType{
					ObjectType: types.ObjectType{
						AttrTypes: CertificateValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"certificate_management_policy": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"authority": schema.StringAttribute{
						Computed:            true,
						Description:         "certificate authority to request certificates from. The only supported value is letsencrypt.\n",
						MarkdownDescription: "certificate authority to request certificates from. The only supported value is letsencrypt.\n",
					},
					"private_key_type": schema.StringAttribute{
						Computed:            true,
						Description:         "type of private key to use when requesting certificates. Defaults to ecdsa, can be either rsa or ecdsa.\n",
						MarkdownDescription: "type of private key to use when requesting certificates. Defaults to ecdsa, can be either rsa or ecdsa.\n",
					},
				},
				CustomType: CertificateManagementPolicyType{
					ObjectType: types.ObjectType{
						AttrTypes: CertificateManagementPolicyValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"certificate_management_status": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"provisioning_job": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"error_code": schema.StringAttribute{
								Computed:            true,
								Description:         "if present, an error code indicating why provisioning is failing. It may be either a temporary condition (INTERNAL_ERROR), or a permanent one the user must correct (DNS_ERROR).\n",
								MarkdownDescription: "if present, an error code indicating why provisioning is failing. It may be either a temporary condition (INTERNAL_ERROR), or a permanent one the user must correct (DNS_ERROR).\n",
							},
							"msg": schema.StringAttribute{
								Computed:            true,
								Description:         "a message describing the current status or error\n",
								MarkdownDescription: "a message describing the current status or error\n",
							},
							"retries_at": schema.StringAttribute{
								Computed:            true,
								Description:         "timestamp when the provisioning job will be retried\n",
								MarkdownDescription: "timestamp when the provisioning job will be retried\n",
							},
							"started_at": schema.StringAttribute{
								Computed:            true,
								Description:         "timestamp when the provisioning job started, RFC 3339 format\n",
								MarkdownDescription: "timestamp when the provisioning job started, RFC 3339 format\n",
							},
						},
						CustomType: ProvisioningJobType{
							ObjectType: types.ObjectType{
								AttrTypes: ProvisioningJobValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
					"renews_at": schema.StringAttribute{
						Computed:            true,
						Description:         "timestamp when the next renewal will be requested, RFC 3339 format\n",
						MarkdownDescription: "timestamp when the next renewal will be requested, RFC 3339 format\n",
					},
				},
				CustomType: CertificateManagementStatusType{
					ObjectType: types.ObjectType{
						AttrTypes: CertificateManagementStatusValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"cname_target": schema.StringAttribute{
				Computed:            true,
				Description:         "DNS CNAME target for a custom hostname, or null if the reserved domain is a subdomain of an ngrok owned domain (e.g. *.ngrok.app)\n",
				MarkdownDescription: "DNS CNAME target for a custom hostname, or null if the reserved domain is a subdomain of an ngrok owned domain (e.g. *.ngrok.app)\n",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the reserved domain was created, RFC 3339 format\n",
				MarkdownDescription: "timestamp when the reserved domain was created, RFC 3339 format\n",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "human-readable description of what this reserved domain will be used for\n",
				MarkdownDescription: "human-readable description of what this reserved domain will be used for\n",
			},
			"domain": schema.StringAttribute{
				Computed:            true,
				Description:         "hostname of the reserved domain\n",
				MarkdownDescription: "hostname of the reserved domain\n",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "a resource identifier\n",
				MarkdownDescription: "a resource identifier\n",
			},
			"metadata": schema.StringAttribute{
				Computed:            true,
				Description:         "arbitrary user-defined machine-readable data of this reserved domain. Optional, max 4096 bytes.\n",
				MarkdownDescription: "arbitrary user-defined machine-readable data of this reserved domain. Optional, max 4096 bytes.\n",
			},
			"region": schema.StringAttribute{
				Computed:            true,
				Description:         "deprecated: With the launch of the ngrok Global Network domains traffic is now handled globally. This field applied only to endpoints. Note that agents may still connect to specific regions. Optional, null by default. (au, eu, ap, us, jp, in, sa)\n",
				MarkdownDescription: "deprecated: With the launch of the ngrok Global Network domains traffic is now handled globally. This field applied only to endpoints. Note that agents may still connect to specific regions. Optional, null by default. (au, eu, ap, us, jp, in, sa)\n",
			},
			"resolves_to": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"value": schema.StringAttribute{
							Computed:            true,
							Description:         "accepts an ngrok point-of-presence shortcode, or \"global\"\n",
							MarkdownDescription: "accepts an ngrok point-of-presence shortcode, or \"global\"\n",
						},
					},
					CustomType: ResolvesToType{
						ObjectType: types.ObjectType{
							AttrTypes: ResolvesToValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "DNS resolver targets configured for the reserved domain, or empty for \"global\" resolution.\n",
				MarkdownDescription: "DNS resolver targets configured for the reserved domain, or empty for \"global\" resolution.\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI of the reserved domain API resource\n",
				MarkdownDescription: "URI of the reserved domain API resource\n",
			},
		},
	}
}

type ReservedDomainModel struct {
	AcmeChallengeCnameTarget    types.String                     `tfsdk:"acme_challenge_cname_target"`
	Certificate                 CertificateValue                 `tfsdk:"certificate"`
	CertificateManagementPolicy CertificateManagementPolicyValue `tfsdk:"certificate_management_policy"`
	CertificateManagementStatus CertificateManagementStatusValue `tfsdk:"certificate_management_status"`
	CnameTarget                 types.String                     `tfsdk:"cname_target"`
	CreatedAt                   types.String                     `tfsdk:"created_at"`
	Description                 types.String                     `tfsdk:"description"`
	Domain                      types.String                     `tfsdk:"domain"`
	Id                          types.String                     `tfsdk:"id"`
	Metadata                    types.String                     `tfsdk:"metadata"`
	Region                      types.String                     `tfsdk:"region"`
	ResolvesTo                  types.List                       `tfsdk:"resolves_to"`
	Uri                         types.String                     `tfsdk:"uri"`
}

var _ basetypes.ObjectTypable = CertificateType{}

type CertificateType struct {
	basetypes.ObjectType
}

func (t CertificateType) Equal(o attr.Type) bool {
	other, ok := o.(CertificateType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CertificateType) String() string {
	return "CertificateType"
}

func (t CertificateType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CertificateValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewCertificateValueNull() CertificateValue {
	return CertificateValue{
		state: attr.ValueStateNull,
	}
}

func NewCertificateValueUnknown() CertificateValue {
	return CertificateValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCertificateValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CertificateValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CertificateValue Attribute Value",
				"While creating a CertificateValue value, a missing attribute value was detected. "+
					"A CertificateValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CertificateValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CertificateValue Attribute Type",
				"While creating a CertificateValue value, an invalid attribute value was detected. "+
					"A CertificateValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CertificateValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CertificateValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CertificateValue Attribute Value",
				"While creating a CertificateValue value, an extra attribute value was detected. "+
					"A CertificateValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CertificateValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCertificateValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewCertificateValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewCertificateValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewCertificateValueUnknown(), diags
	}

	return CertificateValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewCertificateValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CertificateValue {
	object, diags := NewCertificateValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCertificateValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CertificateType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCertificateValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCertificateValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCertificateValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCertificateValueMust(CertificateValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CertificateType) ValueType(ctx context.Context) attr.Value {
	return CertificateValue{}
}

var _ basetypes.ObjectValuable = CertificateValue{}

type CertificateValue struct {
	Id    basetypes.StringValue `tfsdk:"id"`
	Uri   basetypes.StringValue `tfsdk:"uri"`
	state attr.ValueState
}

func (v CertificateValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CertificateValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CertificateValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CertificateValue) String() string {
	return "CertificateValue"
}

func (v CertificateValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":  v.Id,
			"uri": v.Uri,
		})

	return objVal, diags
}

func (v CertificateValue) Equal(o attr.Value) bool {
	other, ok := o.(CertificateValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v CertificateValue) Type(ctx context.Context) attr.Type {
	return CertificateType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CertificateValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = CertificateManagementPolicyType{}

type CertificateManagementPolicyType struct {
	basetypes.ObjectType
}

func (t CertificateManagementPolicyType) Equal(o attr.Type) bool {
	other, ok := o.(CertificateManagementPolicyType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CertificateManagementPolicyType) String() string {
	return "CertificateManagementPolicyType"
}

func (t CertificateManagementPolicyType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	authorityAttribute, ok := attributes["authority"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`authority is missing from object`)

		return nil, diags
	}

	authorityVal, ok := authorityAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`authority expected to be basetypes.StringValue, was: %T`, authorityAttribute))
	}

	privateKeyTypeAttribute, ok := attributes["private_key_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`private_key_type is missing from object`)

		return nil, diags
	}

	privateKeyTypeVal, ok := privateKeyTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`private_key_type expected to be basetypes.StringValue, was: %T`, privateKeyTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CertificateManagementPolicyValue{
		Authority:      authorityVal,
		PrivateKeyType: privateKeyTypeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewCertificateManagementPolicyValueNull() CertificateManagementPolicyValue {
	return CertificateManagementPolicyValue{
		state: attr.ValueStateNull,
	}
}

func NewCertificateManagementPolicyValueUnknown() CertificateManagementPolicyValue {
	return CertificateManagementPolicyValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCertificateManagementPolicyValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CertificateManagementPolicyValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CertificateManagementPolicyValue Attribute Value",
				"While creating a CertificateManagementPolicyValue value, a missing attribute value was detected. "+
					"A CertificateManagementPolicyValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CertificateManagementPolicyValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CertificateManagementPolicyValue Attribute Type",
				"While creating a CertificateManagementPolicyValue value, an invalid attribute value was detected. "+
					"A CertificateManagementPolicyValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CertificateManagementPolicyValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CertificateManagementPolicyValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CertificateManagementPolicyValue Attribute Value",
				"While creating a CertificateManagementPolicyValue value, an extra attribute value was detected. "+
					"A CertificateManagementPolicyValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CertificateManagementPolicyValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCertificateManagementPolicyValueUnknown(), diags
	}

	authorityAttribute, ok := attributes["authority"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`authority is missing from object`)

		return NewCertificateManagementPolicyValueUnknown(), diags
	}

	authorityVal, ok := authorityAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`authority expected to be basetypes.StringValue, was: %T`, authorityAttribute))
	}

	privateKeyTypeAttribute, ok := attributes["private_key_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`private_key_type is missing from object`)

		return NewCertificateManagementPolicyValueUnknown(), diags
	}

	privateKeyTypeVal, ok := privateKeyTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`private_key_type expected to be basetypes.StringValue, was: %T`, privateKeyTypeAttribute))
	}

	if diags.HasError() {
		return NewCertificateManagementPolicyValueUnknown(), diags
	}

	return CertificateManagementPolicyValue{
		Authority:      authorityVal,
		PrivateKeyType: privateKeyTypeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewCertificateManagementPolicyValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CertificateManagementPolicyValue {
	object, diags := NewCertificateManagementPolicyValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCertificateManagementPolicyValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CertificateManagementPolicyType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCertificateManagementPolicyValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCertificateManagementPolicyValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCertificateManagementPolicyValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCertificateManagementPolicyValueMust(CertificateManagementPolicyValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CertificateManagementPolicyType) ValueType(ctx context.Context) attr.Value {
	return CertificateManagementPolicyValue{}
}

var _ basetypes.ObjectValuable = CertificateManagementPolicyValue{}

type CertificateManagementPolicyValue struct {
	Authority      basetypes.StringValue `tfsdk:"authority"`
	PrivateKeyType basetypes.StringValue `tfsdk:"private_key_type"`
	state          attr.ValueState
}

func (v CertificateManagementPolicyValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["authority"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["private_key_type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Authority.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["authority"] = val

		val, err = v.PrivateKeyType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["private_key_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CertificateManagementPolicyValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CertificateManagementPolicyValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CertificateManagementPolicyValue) String() string {
	return "CertificateManagementPolicyValue"
}

func (v CertificateManagementPolicyValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"authority":        basetypes.StringType{},
		"private_key_type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"authority":        v.Authority,
			"private_key_type": v.PrivateKeyType,
		})

	return objVal, diags
}

func (v CertificateManagementPolicyValue) Equal(o attr.Value) bool {
	other, ok := o.(CertificateManagementPolicyValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Authority.Equal(other.Authority) {
		return false
	}

	if !v.PrivateKeyType.Equal(other.PrivateKeyType) {
		return false
	}

	return true
}

func (v CertificateManagementPolicyValue) Type(ctx context.Context) attr.Type {
	return CertificateManagementPolicyType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CertificateManagementPolicyValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"authority":        basetypes.StringType{},
		"private_key_type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = CertificateManagementStatusType{}

type CertificateManagementStatusType struct {
	basetypes.ObjectType
}

func (t CertificateManagementStatusType) Equal(o attr.Type) bool {
	other, ok := o.(CertificateManagementStatusType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CertificateManagementStatusType) String() string {
	return "CertificateManagementStatusType"
}

func (t CertificateManagementStatusType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	provisioningJobAttribute, ok := attributes["provisioning_job"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provisioning_job is missing from object`)

		return nil, diags
	}

	provisioningJobVal, ok := provisioningJobAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provisioning_job expected to be basetypes.ObjectValue, was: %T`, provisioningJobAttribute))
	}

	renewsAtAttribute, ok := attributes["renews_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`renews_at is missing from object`)

		return nil, diags
	}

	renewsAtVal, ok := renewsAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`renews_at expected to be basetypes.StringValue, was: %T`, renewsAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CertificateManagementStatusValue{
		ProvisioningJob: provisioningJobVal,
		RenewsAt:        renewsAtVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewCertificateManagementStatusValueNull() CertificateManagementStatusValue {
	return CertificateManagementStatusValue{
		state: attr.ValueStateNull,
	}
}

func NewCertificateManagementStatusValueUnknown() CertificateManagementStatusValue {
	return CertificateManagementStatusValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCertificateManagementStatusValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CertificateManagementStatusValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CertificateManagementStatusValue Attribute Value",
				"While creating a CertificateManagementStatusValue value, a missing attribute value was detected. "+
					"A CertificateManagementStatusValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CertificateManagementStatusValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CertificateManagementStatusValue Attribute Type",
				"While creating a CertificateManagementStatusValue value, an invalid attribute value was detected. "+
					"A CertificateManagementStatusValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CertificateManagementStatusValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CertificateManagementStatusValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CertificateManagementStatusValue Attribute Value",
				"While creating a CertificateManagementStatusValue value, an extra attribute value was detected. "+
					"A CertificateManagementStatusValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CertificateManagementStatusValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCertificateManagementStatusValueUnknown(), diags
	}

	provisioningJobAttribute, ok := attributes["provisioning_job"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provisioning_job is missing from object`)

		return NewCertificateManagementStatusValueUnknown(), diags
	}

	provisioningJobVal, ok := provisioningJobAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provisioning_job expected to be basetypes.ObjectValue, was: %T`, provisioningJobAttribute))
	}

	renewsAtAttribute, ok := attributes["renews_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`renews_at is missing from object`)

		return NewCertificateManagementStatusValueUnknown(), diags
	}

	renewsAtVal, ok := renewsAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`renews_at expected to be basetypes.StringValue, was: %T`, renewsAtAttribute))
	}

	if diags.HasError() {
		return NewCertificateManagementStatusValueUnknown(), diags
	}

	return CertificateManagementStatusValue{
		ProvisioningJob: provisioningJobVal,
		RenewsAt:        renewsAtVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewCertificateManagementStatusValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CertificateManagementStatusValue {
	object, diags := NewCertificateManagementStatusValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCertificateManagementStatusValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CertificateManagementStatusType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCertificateManagementStatusValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCertificateManagementStatusValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCertificateManagementStatusValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCertificateManagementStatusValueMust(CertificateManagementStatusValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CertificateManagementStatusType) ValueType(ctx context.Context) attr.Value {
	return CertificateManagementStatusValue{}
}

var _ basetypes.ObjectValuable = CertificateManagementStatusValue{}

type CertificateManagementStatusValue struct {
	ProvisioningJob basetypes.ObjectValue `tfsdk:"provisioning_job"`
	RenewsAt        basetypes.StringValue `tfsdk:"renews_at"`
	state           attr.ValueState
}

func (v CertificateManagementStatusValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["provisioning_job"] = basetypes.ObjectType{
		AttrTypes: ProvisioningJobValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["renews_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.ProvisioningJob.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["provisioning_job"] = val

		val, err = v.RenewsAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["renews_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CertificateManagementStatusValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CertificateManagementStatusValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CertificateManagementStatusValue) String() string {
	return "CertificateManagementStatusValue"
}

func (v CertificateManagementStatusValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var provisioningJob basetypes.ObjectValue

	if v.ProvisioningJob.IsNull() {
		provisioningJob = types.ObjectNull(
			ProvisioningJobValue{}.AttributeTypes(ctx),
		)
	}

	if v.ProvisioningJob.IsUnknown() {
		provisioningJob = types.ObjectUnknown(
			ProvisioningJobValue{}.AttributeTypes(ctx),
		)
	}

	if !v.ProvisioningJob.IsNull() && !v.ProvisioningJob.IsUnknown() {
		provisioningJob = types.ObjectValueMust(
			ProvisioningJobValue{}.AttributeTypes(ctx),
			v.ProvisioningJob.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"provisioning_job": basetypes.ObjectType{
			AttrTypes: ProvisioningJobValue{}.AttributeTypes(ctx),
		},
		"renews_at": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"provisioning_job": provisioningJob,
			"renews_at":        v.RenewsAt,
		})

	return objVal, diags
}

func (v CertificateManagementStatusValue) Equal(o attr.Value) bool {
	other, ok := o.(CertificateManagementStatusValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ProvisioningJob.Equal(other.ProvisioningJob) {
		return false
	}

	if !v.RenewsAt.Equal(other.RenewsAt) {
		return false
	}

	return true
}

func (v CertificateManagementStatusValue) Type(ctx context.Context) attr.Type {
	return CertificateManagementStatusType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CertificateManagementStatusValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"provisioning_job": basetypes.ObjectType{
			AttrTypes: ProvisioningJobValue{}.AttributeTypes(ctx),
		},
		"renews_at": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ProvisioningJobType{}

type ProvisioningJobType struct {
	basetypes.ObjectType
}

func (t ProvisioningJobType) Equal(o attr.Type) bool {
	other, ok := o.(ProvisioningJobType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ProvisioningJobType) String() string {
	return "ProvisioningJobType"
}

func (t ProvisioningJobType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	errorCodeAttribute, ok := attributes["error_code"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`error_code is missing from object`)

		return nil, diags
	}

	errorCodeVal, ok := errorCodeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`error_code expected to be basetypes.StringValue, was: %T`, errorCodeAttribute))
	}

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return nil, diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	retriesAtAttribute, ok := attributes["retries_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`retries_at is missing from object`)

		return nil, diags
	}

	retriesAtVal, ok := retriesAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`retries_at expected to be basetypes.StringValue, was: %T`, retriesAtAttribute))
	}

	startedAtAttribute, ok := attributes["started_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`started_at is missing from object`)

		return nil, diags
	}

	startedAtVal, ok := startedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`started_at expected to be basetypes.StringValue, was: %T`, startedAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ProvisioningJobValue{
		ErrorCode: errorCodeVal,
		Msg:       msgVal,
		RetriesAt: retriesAtVal,
		StartedAt: startedAtVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewProvisioningJobValueNull() ProvisioningJobValue {
	return ProvisioningJobValue{
		state: attr.ValueStateNull,
	}
}

func NewProvisioningJobValueUnknown() ProvisioningJobValue {
	return ProvisioningJobValue{
		state: attr.ValueStateUnknown,
	}
}

func NewProvisioningJobValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ProvisioningJobValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ProvisioningJobValue Attribute Value",
				"While creating a ProvisioningJobValue value, a missing attribute value was detected. "+
					"A ProvisioningJobValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProvisioningJobValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ProvisioningJobValue Attribute Type",
				"While creating a ProvisioningJobValue value, an invalid attribute value was detected. "+
					"A ProvisioningJobValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProvisioningJobValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ProvisioningJobValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ProvisioningJobValue Attribute Value",
				"While creating a ProvisioningJobValue value, an extra attribute value was detected. "+
					"A ProvisioningJobValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ProvisioningJobValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewProvisioningJobValueUnknown(), diags
	}

	errorCodeAttribute, ok := attributes["error_code"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`error_code is missing from object`)

		return NewProvisioningJobValueUnknown(), diags
	}

	errorCodeVal, ok := errorCodeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`error_code expected to be basetypes.StringValue, was: %T`, errorCodeAttribute))
	}

	msgAttribute, ok := attributes["msg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`msg is missing from object`)

		return NewProvisioningJobValueUnknown(), diags
	}

	msgVal, ok := msgAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`msg expected to be basetypes.StringValue, was: %T`, msgAttribute))
	}

	retriesAtAttribute, ok := attributes["retries_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`retries_at is missing from object`)

		return NewProvisioningJobValueUnknown(), diags
	}

	retriesAtVal, ok := retriesAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`retries_at expected to be basetypes.StringValue, was: %T`, retriesAtAttribute))
	}

	startedAtAttribute, ok := attributes["started_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`started_at is missing from object`)

		return NewProvisioningJobValueUnknown(), diags
	}

	startedAtVal, ok := startedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`started_at expected to be basetypes.StringValue, was: %T`, startedAtAttribute))
	}

	if diags.HasError() {
		return NewProvisioningJobValueUnknown(), diags
	}

	return ProvisioningJobValue{
		ErrorCode: errorCodeVal,
		Msg:       msgVal,
		RetriesAt: retriesAtVal,
		StartedAt: startedAtVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewProvisioningJobValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ProvisioningJobValue {
	object, diags := NewProvisioningJobValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewProvisioningJobValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ProvisioningJobType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewProvisioningJobValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewProvisioningJobValueUnknown(), nil
	}

	if in.IsNull() {
		return NewProvisioningJobValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewProvisioningJobValueMust(ProvisioningJobValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ProvisioningJobType) ValueType(ctx context.Context) attr.Value {
	return ProvisioningJobValue{}
}

var _ basetypes.ObjectValuable = ProvisioningJobValue{}

type ProvisioningJobValue struct {
	ErrorCode basetypes.StringValue `tfsdk:"error_code"`
	Msg       basetypes.StringValue `tfsdk:"msg"`
	RetriesAt basetypes.StringValue `tfsdk:"retries_at"`
	StartedAt basetypes.StringValue `tfsdk:"started_at"`
	state     attr.ValueState
}

func (v ProvisioningJobValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["error_code"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["msg"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["retries_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["started_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.ErrorCode.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["error_code"] = val

		val, err = v.Msg.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["msg"] = val

		val, err = v.RetriesAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["retries_at"] = val

		val, err = v.StartedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["started_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ProvisioningJobValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ProvisioningJobValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ProvisioningJobValue) String() string {
	return "ProvisioningJobValue"
}

func (v ProvisioningJobValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"error_code": basetypes.StringType{},
		"msg":        basetypes.StringType{},
		"retries_at": basetypes.StringType{},
		"started_at": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"error_code": v.ErrorCode,
			"msg":        v.Msg,
			"retries_at": v.RetriesAt,
			"started_at": v.StartedAt,
		})

	return objVal, diags
}

func (v ProvisioningJobValue) Equal(o attr.Value) bool {
	other, ok := o.(ProvisioningJobValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ErrorCode.Equal(other.ErrorCode) {
		return false
	}

	if !v.Msg.Equal(other.Msg) {
		return false
	}

	if !v.RetriesAt.Equal(other.RetriesAt) {
		return false
	}

	if !v.StartedAt.Equal(other.StartedAt) {
		return false
	}

	return true
}

func (v ProvisioningJobValue) Type(ctx context.Context) attr.Type {
	return ProvisioningJobType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ProvisioningJobValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"error_code": basetypes.StringType{},
		"msg":        basetypes.StringType{},
		"retries_at": basetypes.StringType{},
		"started_at": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ResolvesToType{}

type ResolvesToType struct {
	basetypes.ObjectType
}

func (t ResolvesToType) Equal(o attr.Type) bool {
	other, ok := o.(ResolvesToType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ResolvesToType) String() string {
	return "ResolvesToType"
}

func (t ResolvesToType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return nil, diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ResolvesToValue{
		Value: valueVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewResolvesToValueNull() ResolvesToValue {
	return ResolvesToValue{
		state: attr.ValueStateNull,
	}
}

func NewResolvesToValueUnknown() ResolvesToValue {
	return ResolvesToValue{
		state: attr.ValueStateUnknown,
	}
}

func NewResolvesToValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ResolvesToValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ResolvesToValue Attribute Value",
				"While creating a ResolvesToValue value, a missing attribute value was detected. "+
					"A ResolvesToValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResolvesToValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ResolvesToValue Attribute Type",
				"While creating a ResolvesToValue value, an invalid attribute value was detected. "+
					"A ResolvesToValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResolvesToValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ResolvesToValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ResolvesToValue Attribute Value",
				"While creating a ResolvesToValue value, an extra attribute value was detected. "+
					"A ResolvesToValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ResolvesToValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewResolvesToValueUnknown(), diags
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return NewResolvesToValueUnknown(), diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return NewResolvesToValueUnknown(), diags
	}

	return ResolvesToValue{
		Value: valueVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewResolvesToValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ResolvesToValue {
	object, diags := NewResolvesToValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewResolvesToValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ResolvesToType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewResolvesToValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewResolvesToValueUnknown(), nil
	}

	if in.IsNull() {
		return NewResolvesToValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewResolvesToValueMust(ResolvesToValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ResolvesToType) ValueType(ctx context.Context) attr.Value {
	return ResolvesToValue{}
}

var _ basetypes.ObjectValuable = ResolvesToValue{}

type ResolvesToValue struct {
	Value basetypes.StringValue `tfsdk:"value"`
	state attr.ValueState
}

func (v ResolvesToValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["value"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Value.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ResolvesToValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ResolvesToValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ResolvesToValue) String() string {
	return "ResolvesToValue"
}

func (v ResolvesToValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"value": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"value": v.Value,
		})

	return objVal, diags
}

func (v ResolvesToValue) Equal(o attr.Value) bool {
	other, ok := o.(ResolvesToValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Value.Equal(other.Value) {
		return false
	}

	return true
}

func (v ResolvesToValue) Type(ctx context.Context) attr.Type {
	return ResolvesToType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ResolvesToValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"value": basetypes.StringType{},
	}
}
