// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_certificate_authority

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CertificateAuthorityDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ca_pem": schema.StringAttribute{
				Computed:            true,
				Description:         "raw PEM of the Certificate Authority\n",
				MarkdownDescription: "raw PEM of the Certificate Authority\n",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the Certificate Authority was created, RFC 3339 format\n",
				MarkdownDescription: "timestamp when the Certificate Authority was created, RFC 3339 format\n",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "human-readable description of this Certificate Authority. optional, max 255 bytes.\n",
				MarkdownDescription: "human-readable description of this Certificate Authority. optional, max 255 bytes.\n",
			},
			"extended_key_usages": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "extended set of actions the private key of this Certificate Authority can be used for\n",
				MarkdownDescription: "extended set of actions the private key of this Certificate Authority can be used for\n",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "a resource identifier\n",
				MarkdownDescription: "a resource identifier\n",
			},
			"key_usages": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "set of actions the private key of this Certificate Authority can be used for\n",
				MarkdownDescription: "set of actions the private key of this Certificate Authority can be used for\n",
			},
			"metadata": schema.StringAttribute{
				Computed:            true,
				Description:         "arbitrary user-defined machine-readable data of this Certificate Authority. optional, max 4096 bytes.\n",
				MarkdownDescription: "arbitrary user-defined machine-readable data of this Certificate Authority. optional, max 4096 bytes.\n",
			},
			"not_after": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when this Certificate Authority becomes invalid, RFC 3339 format\n",
				MarkdownDescription: "timestamp when this Certificate Authority becomes invalid, RFC 3339 format\n",
			},
			"not_before": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when this Certificate Authority becomes valid, RFC 3339 format\n",
				MarkdownDescription: "timestamp when this Certificate Authority becomes valid, RFC 3339 format\n",
			},
			"subject_common_name": schema.StringAttribute{
				Computed:            true,
				Description:         "subject common name of the Certificate Authority\n",
				MarkdownDescription: "subject common name of the Certificate Authority\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI of the Certificate Authority API resource\n",
				MarkdownDescription: "URI of the Certificate Authority API resource\n",
			},
		},
	}
}

type CertificateAuthorityModel struct {
	CaPem             types.String `tfsdk:"ca_pem"`
	CreatedAt         types.String `tfsdk:"created_at"`
	Description       types.String `tfsdk:"description"`
	ExtendedKeyUsages types.List   `tfsdk:"extended_key_usages"`
	Id                types.String `tfsdk:"id"`
	KeyUsages         types.List   `tfsdk:"key_usages"`
	Metadata          types.String `tfsdk:"metadata"`
	NotAfter          types.String `tfsdk:"not_after"`
	NotBefore         types.String `tfsdk:"not_before"`
	SubjectCommonName types.String `tfsdk:"subject_common_name"`
	Uri               types.String `tfsdk:"uri"`
}
