// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_event_destination

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func EventDestinationResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "Timestamp when the Event Destination was created, RFC 3339 format.\n",
				MarkdownDescription: "Timestamp when the Event Destination was created, RFC 3339 format.\n",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Human-readable description of the Event Destination. Optional, max 255 bytes.\n",
				MarkdownDescription: "Human-readable description of the Event Destination. Optional, max 255 bytes.\n",
			},
			"format": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The output format you would like to serialize events into when sending to their target. Currently the only accepted value is `JSON`.\n",
				MarkdownDescription: "The output format you would like to serialize events into when sending to their target. Currently the only accepted value is `JSON`.\n",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier for this Event Destination.\n",
				MarkdownDescription: "Unique identifier for this Event Destination.\n",
			},
			"metadata": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Arbitrary user-defined machine-readable data of this Event Destination. Optional, max 4096 bytes.\n",
				MarkdownDescription: "Arbitrary user-defined machine-readable data of this Event Destination. Optional, max 4096 bytes.\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI of the Event Destination API resource.\n",
				MarkdownDescription: "URI of the Event Destination API resource.\n",
			},
		},
	}
}

type EventDestinationModel struct {
	CreatedAt   types.String `tfsdk:"created_at"`
	Description types.String `tfsdk:"description"`
	Format      types.String `tfsdk:"format"`
	Id          types.String `tfsdk:"id"`
	Metadata    types.String `tfsdk:"metadata"`
	Uri         types.String `tfsdk:"uri"`
}
