// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_api_key

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ApiKeyDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the api key was created, RFC 3339 format\n",
				MarkdownDescription: "timestamp when the api key was created, RFC 3339 format\n",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "human-readable description of what uses the API key to authenticate. optional, max 255 bytes.\n",
				MarkdownDescription: "human-readable description of what uses the API key to authenticate. optional, max 255 bytes.\n",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "a resource identifier\n",
				MarkdownDescription: "a resource identifier\n",
			},
			"metadata": schema.StringAttribute{
				Computed:            true,
				Description:         "arbitrary user-defined data of this API key. optional, max 4096 bytes\n",
				MarkdownDescription: "arbitrary user-defined data of this API key. optional, max 4096 bytes\n",
			},
			"owner_id": schema.StringAttribute{
				Computed:            true,
				Description:         "If supplied at credential creation, ownership will be assigned to the specified User or Bot. Only admins may specify an owner other than themselves. Defaults to the authenticated User or Bot.\n",
				MarkdownDescription: "If supplied at credential creation, ownership will be assigned to the specified User or Bot. Only admins may specify an owner other than themselves. Defaults to the authenticated User or Bot.\n",
			},
			"token": schema.StringAttribute{
				Computed:            true,
				Description:         "the bearer token that can be placed into the Authorization header to authenticate request to the ngrok API. **This value is only available one time, on the API response from key creation. Otherwise it is null.**\n",
				MarkdownDescription: "the bearer token that can be placed into the Authorization header to authenticate request to the ngrok API. **This value is only available one time, on the API response from key creation. Otherwise it is null.**\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI to the API resource of this API key\n",
				MarkdownDescription: "URI to the API resource of this API key\n",
			},
		},
	}
}

type ApiKeyModel struct {
	CreatedAt   types.String `tfsdk:"created_at"`
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Metadata    types.String `tfsdk:"metadata"`
	OwnerId     types.String `tfsdk:"owner_id"`
	Token       types.String `tfsdk:"token"`
	Uri         types.String `tfsdk:"uri"`
}
