// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_tunnel_session

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func TunnelSessionDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"agent_version": schema.StringAttribute{
				Computed:            true,
				Description:         "version of the ngrok agent that started this ngrok tunnel session\n",
				MarkdownDescription: "version of the ngrok agent that started this ngrok tunnel session\n",
			},
			"credential": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "a resource identifier\n",
						MarkdownDescription: "a resource identifier\n",
					},
					"uri": schema.StringAttribute{
						Computed:            true,
						Description:         "a uri for locating a resource\n",
						MarkdownDescription: "a uri for locating a resource\n",
					},
				},
				CustomType: CredentialType{
					ObjectType: types.ObjectType{
						AttrTypes: CredentialValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "a resource identifier\n",
				MarkdownDescription: "a resource identifier\n",
			},
			"ip": schema.StringAttribute{
				Computed:            true,
				Description:         "source ip address of the tunnel session\n",
				MarkdownDescription: "source ip address of the tunnel session\n",
			},
			"metadata": schema.StringAttribute{
				Computed:            true,
				Description:         "arbitrary user-defined data specified in the metadata property in the ngrok configuration file. See the metadata configuration option\n",
				MarkdownDescription: "arbitrary user-defined data specified in the metadata property in the ngrok configuration file. See the metadata configuration option\n",
			},
			"os": schema.StringAttribute{
				Computed:            true,
				Description:         "operating system of the host the ngrok agent is running on\n",
				MarkdownDescription: "operating system of the host the ngrok agent is running on\n",
			},
			"region": schema.StringAttribute{
				Computed:            true,
				Description:         "the ngrok region identifier in which this tunnel session was started\n",
				MarkdownDescription: "the ngrok region identifier in which this tunnel session was started\n",
			},
			"started_at": schema.StringAttribute{
				Computed:            true,
				Description:         "time when the tunnel session first connected to the ngrok servers\n",
				MarkdownDescription: "time when the tunnel session first connected to the ngrok servers\n",
			},
			"transport": schema.StringAttribute{
				Computed:            true,
				Description:         "the transport protocol used to start the tunnel session. Either `ngrok/v2` or `ssh`\n",
				MarkdownDescription: "the transport protocol used to start the tunnel session. Either `ngrok/v2` or `ssh`\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI to the API resource of the tunnel session\n",
				MarkdownDescription: "URI to the API resource of the tunnel session\n",
			},
		},
	}
}

type TunnelSessionModel struct {
	AgentVersion types.String    `tfsdk:"agent_version"`
	Credential   CredentialValue `tfsdk:"credential"`
	Id           types.String    `tfsdk:"id"`
	Ip           types.String    `tfsdk:"ip"`
	Metadata     types.String    `tfsdk:"metadata"`
	Os           types.String    `tfsdk:"os"`
	Region       types.String    `tfsdk:"region"`
	StartedAt    types.String    `tfsdk:"started_at"`
	Transport    types.String    `tfsdk:"transport"`
	Uri          types.String    `tfsdk:"uri"`
}

var _ basetypes.ObjectTypable = CredentialType{}

type CredentialType struct {
	basetypes.ObjectType
}

func (t CredentialType) Equal(o attr.Type) bool {
	other, ok := o.(CredentialType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CredentialType) String() string {
	return "CredentialType"
}

func (t CredentialType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CredentialValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewCredentialValueNull() CredentialValue {
	return CredentialValue{
		state: attr.ValueStateNull,
	}
}

func NewCredentialValueUnknown() CredentialValue {
	return CredentialValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCredentialValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CredentialValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CredentialValue Attribute Value",
				"While creating a CredentialValue value, a missing attribute value was detected. "+
					"A CredentialValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CredentialValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CredentialValue Attribute Type",
				"While creating a CredentialValue value, an invalid attribute value was detected. "+
					"A CredentialValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CredentialValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CredentialValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CredentialValue Attribute Value",
				"While creating a CredentialValue value, an extra attribute value was detected. "+
					"A CredentialValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CredentialValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCredentialValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewCredentialValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewCredentialValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewCredentialValueUnknown(), diags
	}

	return CredentialValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewCredentialValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CredentialValue {
	object, diags := NewCredentialValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCredentialValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CredentialType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCredentialValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCredentialValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCredentialValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCredentialValueMust(CredentialValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CredentialType) ValueType(ctx context.Context) attr.Value {
	return CredentialValue{}
}

var _ basetypes.ObjectValuable = CredentialValue{}

type CredentialValue struct {
	Id    basetypes.StringValue `tfsdk:"id"`
	Uri   basetypes.StringValue `tfsdk:"uri"`
	state attr.ValueState
}

func (v CredentialValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CredentialValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CredentialValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CredentialValue) String() string {
	return "CredentialValue"
}

func (v CredentialValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":  v.Id,
			"uri": v.Uri,
		})

	return objVal, diags
}

func (v CredentialValue) Equal(o attr.Value) bool {
	other, ok := o.(CredentialValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v CredentialValue) Type(ctx context.Context) attr.Type {
	return CredentialType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CredentialValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}
}
