// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_ssh_credential

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SshCredentialDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"acl": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "optional list of ACL rules. If unspecified, the credential will have no restrictions. The only allowed ACL rule at this time is the `bind` rule. The `bind` rule allows the caller to restrict what domains, addresses, and labels the token is allowed to bind. For example, to allow the token to open a tunnel on example.ngrok.io your ACL would include the rule `bind:example.ngrok.io`. Bind rules for domains may specify a leading wildcard to match multiple domains with a common suffix. For example, you may specify a rule of `bind:*.example.com` which will allow `x.example.com`, `y.example.com`, `*.example.com`, etc. Bind rules for labels may specify a wildcard key and/or value to match multiple labels. For example, you may specify a rule of `bind:*=example` which will allow `x=example`, `y=example`, etc. A rule of `'*'` is equivalent to no acl at all and will explicitly permit all actions.\n",
				MarkdownDescription: "optional list of ACL rules. If unspecified, the credential will have no restrictions. The only allowed ACL rule at this time is the `bind` rule. The `bind` rule allows the caller to restrict what domains, addresses, and labels the token is allowed to bind. For example, to allow the token to open a tunnel on example.ngrok.io your ACL would include the rule `bind:example.ngrok.io`. Bind rules for domains may specify a leading wildcard to match multiple domains with a common suffix. For example, you may specify a rule of `bind:*.example.com` which will allow `x.example.com`, `y.example.com`, `*.example.com`, etc. Bind rules for labels may specify a wildcard key and/or value to match multiple labels. For example, you may specify a rule of `bind:*=example` which will allow `x=example`, `y=example`, etc. A rule of `'*'` is equivalent to no acl at all and will explicitly permit all actions.\n",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the ssh credential was created, RFC 3339 format\n",
				MarkdownDescription: "timestamp when the ssh credential was created, RFC 3339 format\n",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "human-readable description of who or what will use the ssh credential to authenticate. Optional, max 255 bytes.\n",
				MarkdownDescription: "human-readable description of who or what will use the ssh credential to authenticate. Optional, max 255 bytes.\n",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "a resource identifier\n",
				MarkdownDescription: "a resource identifier\n",
			},
			"metadata": schema.StringAttribute{
				Computed:            true,
				Description:         "arbitrary user-defined machine-readable data of this ssh credential. Optional, max 4096 bytes.\n",
				MarkdownDescription: "arbitrary user-defined machine-readable data of this ssh credential. Optional, max 4096 bytes.\n",
			},
			"owner_id": schema.StringAttribute{
				Computed:            true,
				Description:         "If supplied at credential creation, ownership will be assigned to the specified User or Bot. Only admins may specify an owner other than themselves. Defaults to the authenticated User or Bot.\n",
				MarkdownDescription: "If supplied at credential creation, ownership will be assigned to the specified User or Bot. Only admins may specify an owner other than themselves. Defaults to the authenticated User or Bot.\n",
			},
			"public_key": schema.StringAttribute{
				Computed:            true,
				Description:         "the PEM-encoded public key of the SSH keypair that will be used to authenticate\n",
				MarkdownDescription: "the PEM-encoded public key of the SSH keypair that will be used to authenticate\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI of the ssh credential API resource\n",
				MarkdownDescription: "URI of the ssh credential API resource\n",
			},
		},
	}
}

type SshCredentialModel struct {
	Acl         types.List   `tfsdk:"acl"`
	CreatedAt   types.String `tfsdk:"created_at"`
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Metadata    types.String `tfsdk:"metadata"`
	OwnerId     types.String `tfsdk:"owner_id"`
	PublicKey   types.String `tfsdk:"public_key"`
	Uri         types.String `tfsdk:"uri"`
}
