// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_cloud_endpoint

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CloudEndpointResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bindings": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "the bindings associated with this endpoint\n",
				MarkdownDescription: "the bindings associated with this endpoint\n",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the endpoint was created in RFC 3339 format\n",
				MarkdownDescription: "timestamp when the endpoint was created in RFC 3339 format\n",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "user-supplied description of the associated tunnel\n",
				MarkdownDescription: "user-supplied description of the associated tunnel\n",
			},
			"domain": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "a resource identifier\n",
						MarkdownDescription: "a resource identifier\n",
					},
					"uri": schema.StringAttribute{
						Computed:            true,
						Description:         "a uri for locating a resource\n",
						MarkdownDescription: "a uri for locating a resource\n",
					},
				},
				CustomType: DomainType{
					ObjectType: types.ObjectType{
						AttrTypes: DomainValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"edge": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "a resource identifier\n",
						MarkdownDescription: "a resource identifier\n",
					},
					"uri": schema.StringAttribute{
						Computed:            true,
						Description:         "a uri for locating a resource\n",
						MarkdownDescription: "a uri for locating a resource\n",
					},
				},
				CustomType: EdgeType{
					ObjectType: types.ObjectType{
						AttrTypes: EdgeValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"host": schema.StringAttribute{
				Computed:            true,
				Description:         "n/a",
				MarkdownDescription: "n/a",
			},
			"hostport": schema.StringAttribute{
				Computed:            true,
				Description:         "hostport served by this endpoint (hostname:port) -> soon to be deprecated\n",
				MarkdownDescription: "hostport served by this endpoint (hostname:port) -> soon to be deprecated\n",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "unique endpoint resource identifier\n",
				MarkdownDescription: "unique endpoint resource identifier\n",
			},
			"metadata": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "user-supplied metadata of the associated tunnel or edge object\n",
				MarkdownDescription: "user-supplied metadata of the associated tunnel or edge object\n",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "user supplied name for the endpoint\n",
				MarkdownDescription: "user supplied name for the endpoint\n",
			},
			"pooling_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "n/a",
				MarkdownDescription: "n/a",
			},
			"port": schema.Int64Attribute{
				Computed:            true,
				Description:         "n/a",
				MarkdownDescription: "n/a",
			},
			"principal": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "a resource identifier\n",
						MarkdownDescription: "a resource identifier\n",
					},
					"uri": schema.StringAttribute{
						Computed:            true,
						Description:         "a uri for locating a resource\n",
						MarkdownDescription: "a uri for locating a resource\n",
					},
				},
				CustomType: PrincipalType{
					ObjectType: types.ObjectType{
						AttrTypes: PrincipalValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"proto": schema.StringAttribute{
				Computed:            true,
				Description:         "protocol served by this endpoint. one of `http`, `https`, `tcp`, or `tls`\n",
				MarkdownDescription: "protocol served by this endpoint. one of `http`, `https`, `tcp`, or `tls`\n",
			},
			"public_url": schema.StringAttribute{
				Computed:            true,
				Description:         "deprecated [replaced by URL]: URL of the hostport served by this endpoint\n",
				MarkdownDescription: "deprecated [replaced by URL]: URL of the hostport served by this endpoint\n",
			},
			"region": schema.StringAttribute{
				Computed:            true,
				Description:         "identifier of the region this endpoint belongs to\n",
				MarkdownDescription: "identifier of the region this endpoint belongs to\n",
			},
			"scheme": schema.StringAttribute{
				Computed:            true,
				Description:         "n/a",
				MarkdownDescription: "n/a",
			},
			"tcp_addr": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "a resource identifier\n",
						MarkdownDescription: "a resource identifier\n",
					},
					"uri": schema.StringAttribute{
						Computed:            true,
						Description:         "a uri for locating a resource\n",
						MarkdownDescription: "a uri for locating a resource\n",
					},
				},
				CustomType: TcpAddrType{
					ObjectType: types.ObjectType{
						AttrTypes: TcpAddrValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"traffic_policy": schema.StringAttribute{
				Required:            true,
				Description:         "The traffic policy attached to this endpoint\n",
				MarkdownDescription: "The traffic policy attached to this endpoint\n",
			},
			"tunnel": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "a resource identifier\n",
						MarkdownDescription: "a resource identifier\n",
					},
					"uri": schema.StringAttribute{
						Computed:            true,
						Description:         "a uri for locating a resource\n",
						MarkdownDescription: "a uri for locating a resource\n",
					},
				},
				CustomType: TunnelType{
					ObjectType: types.ObjectType{
						AttrTypes: TunnelValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"tunnel_session": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "a resource identifier\n",
						MarkdownDescription: "a resource identifier\n",
					},
					"uri": schema.StringAttribute{
						Computed:            true,
						Description:         "a uri for locating a resource\n",
						MarkdownDescription: "a uri for locating a resource\n",
					},
				},
				CustomType: TunnelSessionType{
					ObjectType: types.ObjectType{
						AttrTypes: TunnelSessionValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"type": schema.StringAttribute{
				Required:            true,
				Description:         "Type of endpoint. Only 'cloud' is currently supported (represents a cloud endpoint). Defaults to 'cloud' if not specified.\n",
				MarkdownDescription: "Type of endpoint. Only 'cloud' is currently supported (represents a cloud endpoint). Defaults to 'cloud' if not specified.\n",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the endpoint was updated in RFC 3339 format\n",
				MarkdownDescription: "timestamp when the endpoint was updated in RFC 3339 format\n",
			},
			"upstream_protocol": schema.StringAttribute{
				Computed:            true,
				Description:         "the protocol the agent uses to forward with\n",
				MarkdownDescription: "the protocol the agent uses to forward with\n",
			},
			"upstream_url": schema.StringAttribute{
				Computed:            true,
				Description:         "the local address the tunnel forwards to\n",
				MarkdownDescription: "the local address the tunnel forwards to\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI of the Cloud Endpoint API resource\n",
				MarkdownDescription: "URI of the Cloud Endpoint API resource\n",
			},
			"url": schema.StringAttribute{
				Required:            true,
				Description:         "the url of the endpoint\n",
				MarkdownDescription: "the url of the endpoint\n",
			},
		},
	}
}

type CloudEndpointModel struct {
	Bindings         types.List         `tfsdk:"bindings"`
	CreatedAt        types.String       `tfsdk:"created_at"`
	Description      types.String       `tfsdk:"description"`
	Domain           DomainValue        `tfsdk:"domain"`
	Edge             EdgeValue          `tfsdk:"edge"`
	Host             types.String       `tfsdk:"host"`
	Hostport         types.String       `tfsdk:"hostport"`
	Id               types.String       `tfsdk:"id"`
	Metadata         types.String       `tfsdk:"metadata"`
	Name             types.String       `tfsdk:"name"`
	PoolingEnabled   types.Bool         `tfsdk:"pooling_enabled"`
	Port             types.Int64        `tfsdk:"port"`
	Principal        PrincipalValue     `tfsdk:"principal"`
	Proto            types.String       `tfsdk:"proto"`
	PublicUrl        types.String       `tfsdk:"public_url"`
	Region           types.String       `tfsdk:"region"`
	Scheme           types.String       `tfsdk:"scheme"`
	TcpAddr          TcpAddrValue       `tfsdk:"tcp_addr"`
	TrafficPolicy    types.String       `tfsdk:"traffic_policy"`
	Tunnel           TunnelValue        `tfsdk:"tunnel"`
	TunnelSession    TunnelSessionValue `tfsdk:"tunnel_session"`
	Type             types.String       `tfsdk:"type"`
	UpdatedAt        types.String       `tfsdk:"updated_at"`
	UpstreamProtocol types.String       `tfsdk:"upstream_protocol"`
	UpstreamUrl      types.String       `tfsdk:"upstream_url"`
	Uri              types.String       `tfsdk:"uri"`
	Url              types.String       `tfsdk:"url"`
}

var _ basetypes.ObjectTypable = DomainType{}

type DomainType struct {
	basetypes.ObjectType
}

func (t DomainType) Equal(o attr.Type) bool {
	other, ok := o.(DomainType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DomainType) String() string {
	return "DomainType"
}

func (t DomainType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DomainValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewDomainValueNull() DomainValue {
	return DomainValue{
		state: attr.ValueStateNull,
	}
}

func NewDomainValueUnknown() DomainValue {
	return DomainValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDomainValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DomainValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DomainValue Attribute Value",
				"While creating a DomainValue value, a missing attribute value was detected. "+
					"A DomainValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DomainValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DomainValue Attribute Type",
				"While creating a DomainValue value, an invalid attribute value was detected. "+
					"A DomainValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DomainValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DomainValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DomainValue Attribute Value",
				"While creating a DomainValue value, an extra attribute value was detected. "+
					"A DomainValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DomainValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDomainValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewDomainValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewDomainValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewDomainValueUnknown(), diags
	}

	return DomainValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewDomainValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DomainValue {
	object, diags := NewDomainValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDomainValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DomainType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDomainValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDomainValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDomainValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDomainValueMust(DomainValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DomainType) ValueType(ctx context.Context) attr.Value {
	return DomainValue{}
}

var _ basetypes.ObjectValuable = DomainValue{}

type DomainValue struct {
	Id    basetypes.StringValue `tfsdk:"id"`
	Uri   basetypes.StringValue `tfsdk:"uri"`
	state attr.ValueState
}

func (v DomainValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DomainValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DomainValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DomainValue) String() string {
	return "DomainValue"
}

func (v DomainValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":  v.Id,
			"uri": v.Uri,
		})

	return objVal, diags
}

func (v DomainValue) Equal(o attr.Value) bool {
	other, ok := o.(DomainValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v DomainValue) Type(ctx context.Context) attr.Type {
	return DomainType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DomainValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = EdgeType{}

type EdgeType struct {
	basetypes.ObjectType
}

func (t EdgeType) Equal(o attr.Type) bool {
	other, ok := o.(EdgeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t EdgeType) String() string {
	return "EdgeType"
}

func (t EdgeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return EdgeValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewEdgeValueNull() EdgeValue {
	return EdgeValue{
		state: attr.ValueStateNull,
	}
}

func NewEdgeValueUnknown() EdgeValue {
	return EdgeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewEdgeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (EdgeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing EdgeValue Attribute Value",
				"While creating a EdgeValue value, a missing attribute value was detected. "+
					"A EdgeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EdgeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid EdgeValue Attribute Type",
				"While creating a EdgeValue value, an invalid attribute value was detected. "+
					"A EdgeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EdgeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("EdgeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra EdgeValue Attribute Value",
				"While creating a EdgeValue value, an extra attribute value was detected. "+
					"A EdgeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra EdgeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewEdgeValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewEdgeValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewEdgeValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewEdgeValueUnknown(), diags
	}

	return EdgeValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewEdgeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) EdgeValue {
	object, diags := NewEdgeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewEdgeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t EdgeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewEdgeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewEdgeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewEdgeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewEdgeValueMust(EdgeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t EdgeType) ValueType(ctx context.Context) attr.Value {
	return EdgeValue{}
}

var _ basetypes.ObjectValuable = EdgeValue{}

type EdgeValue struct {
	Id    basetypes.StringValue `tfsdk:"id"`
	Uri   basetypes.StringValue `tfsdk:"uri"`
	state attr.ValueState
}

func (v EdgeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v EdgeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v EdgeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v EdgeValue) String() string {
	return "EdgeValue"
}

func (v EdgeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":  v.Id,
			"uri": v.Uri,
		})

	return objVal, diags
}

func (v EdgeValue) Equal(o attr.Value) bool {
	other, ok := o.(EdgeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v EdgeValue) Type(ctx context.Context) attr.Type {
	return EdgeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v EdgeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = PrincipalType{}

type PrincipalType struct {
	basetypes.ObjectType
}

func (t PrincipalType) Equal(o attr.Type) bool {
	other, ok := o.(PrincipalType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PrincipalType) String() string {
	return "PrincipalType"
}

func (t PrincipalType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PrincipalValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewPrincipalValueNull() PrincipalValue {
	return PrincipalValue{
		state: attr.ValueStateNull,
	}
}

func NewPrincipalValueUnknown() PrincipalValue {
	return PrincipalValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPrincipalValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PrincipalValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PrincipalValue Attribute Value",
				"While creating a PrincipalValue value, a missing attribute value was detected. "+
					"A PrincipalValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PrincipalValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PrincipalValue Attribute Type",
				"While creating a PrincipalValue value, an invalid attribute value was detected. "+
					"A PrincipalValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PrincipalValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PrincipalValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PrincipalValue Attribute Value",
				"While creating a PrincipalValue value, an extra attribute value was detected. "+
					"A PrincipalValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PrincipalValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPrincipalValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewPrincipalValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewPrincipalValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewPrincipalValueUnknown(), diags
	}

	return PrincipalValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewPrincipalValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PrincipalValue {
	object, diags := NewPrincipalValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPrincipalValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PrincipalType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPrincipalValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPrincipalValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPrincipalValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPrincipalValueMust(PrincipalValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PrincipalType) ValueType(ctx context.Context) attr.Value {
	return PrincipalValue{}
}

var _ basetypes.ObjectValuable = PrincipalValue{}

type PrincipalValue struct {
	Id    basetypes.StringValue `tfsdk:"id"`
	Uri   basetypes.StringValue `tfsdk:"uri"`
	state attr.ValueState
}

func (v PrincipalValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PrincipalValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PrincipalValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PrincipalValue) String() string {
	return "PrincipalValue"
}

func (v PrincipalValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":  v.Id,
			"uri": v.Uri,
		})

	return objVal, diags
}

func (v PrincipalValue) Equal(o attr.Value) bool {
	other, ok := o.(PrincipalValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v PrincipalValue) Type(ctx context.Context) attr.Type {
	return PrincipalType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PrincipalValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TcpAddrType{}

type TcpAddrType struct {
	basetypes.ObjectType
}

func (t TcpAddrType) Equal(o attr.Type) bool {
	other, ok := o.(TcpAddrType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TcpAddrType) String() string {
	return "TcpAddrType"
}

func (t TcpAddrType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TcpAddrValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTcpAddrValueNull() TcpAddrValue {
	return TcpAddrValue{
		state: attr.ValueStateNull,
	}
}

func NewTcpAddrValueUnknown() TcpAddrValue {
	return TcpAddrValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTcpAddrValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TcpAddrValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TcpAddrValue Attribute Value",
				"While creating a TcpAddrValue value, a missing attribute value was detected. "+
					"A TcpAddrValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TcpAddrValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TcpAddrValue Attribute Type",
				"While creating a TcpAddrValue value, an invalid attribute value was detected. "+
					"A TcpAddrValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TcpAddrValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TcpAddrValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TcpAddrValue Attribute Value",
				"While creating a TcpAddrValue value, an extra attribute value was detected. "+
					"A TcpAddrValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TcpAddrValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTcpAddrValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewTcpAddrValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewTcpAddrValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewTcpAddrValueUnknown(), diags
	}

	return TcpAddrValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTcpAddrValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TcpAddrValue {
	object, diags := NewTcpAddrValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTcpAddrValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TcpAddrType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTcpAddrValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTcpAddrValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTcpAddrValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTcpAddrValueMust(TcpAddrValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TcpAddrType) ValueType(ctx context.Context) attr.Value {
	return TcpAddrValue{}
}

var _ basetypes.ObjectValuable = TcpAddrValue{}

type TcpAddrValue struct {
	Id    basetypes.StringValue `tfsdk:"id"`
	Uri   basetypes.StringValue `tfsdk:"uri"`
	state attr.ValueState
}

func (v TcpAddrValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TcpAddrValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TcpAddrValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TcpAddrValue) String() string {
	return "TcpAddrValue"
}

func (v TcpAddrValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":  v.Id,
			"uri": v.Uri,
		})

	return objVal, diags
}

func (v TcpAddrValue) Equal(o attr.Value) bool {
	other, ok := o.(TcpAddrValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v TcpAddrValue) Type(ctx context.Context) attr.Type {
	return TcpAddrType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TcpAddrValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TunnelType{}

type TunnelType struct {
	basetypes.ObjectType
}

func (t TunnelType) Equal(o attr.Type) bool {
	other, ok := o.(TunnelType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TunnelType) String() string {
	return "TunnelType"
}

func (t TunnelType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TunnelValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTunnelValueNull() TunnelValue {
	return TunnelValue{
		state: attr.ValueStateNull,
	}
}

func NewTunnelValueUnknown() TunnelValue {
	return TunnelValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTunnelValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TunnelValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TunnelValue Attribute Value",
				"While creating a TunnelValue value, a missing attribute value was detected. "+
					"A TunnelValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TunnelValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TunnelValue Attribute Type",
				"While creating a TunnelValue value, an invalid attribute value was detected. "+
					"A TunnelValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TunnelValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TunnelValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TunnelValue Attribute Value",
				"While creating a TunnelValue value, an extra attribute value was detected. "+
					"A TunnelValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TunnelValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTunnelValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewTunnelValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewTunnelValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewTunnelValueUnknown(), diags
	}

	return TunnelValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTunnelValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TunnelValue {
	object, diags := NewTunnelValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTunnelValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TunnelType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTunnelValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTunnelValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTunnelValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTunnelValueMust(TunnelValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TunnelType) ValueType(ctx context.Context) attr.Value {
	return TunnelValue{}
}

var _ basetypes.ObjectValuable = TunnelValue{}

type TunnelValue struct {
	Id    basetypes.StringValue `tfsdk:"id"`
	Uri   basetypes.StringValue `tfsdk:"uri"`
	state attr.ValueState
}

func (v TunnelValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TunnelValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TunnelValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TunnelValue) String() string {
	return "TunnelValue"
}

func (v TunnelValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":  v.Id,
			"uri": v.Uri,
		})

	return objVal, diags
}

func (v TunnelValue) Equal(o attr.Value) bool {
	other, ok := o.(TunnelValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v TunnelValue) Type(ctx context.Context) attr.Type {
	return TunnelType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TunnelValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TunnelSessionType{}

type TunnelSessionType struct {
	basetypes.ObjectType
}

func (t TunnelSessionType) Equal(o attr.Type) bool {
	other, ok := o.(TunnelSessionType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TunnelSessionType) String() string {
	return "TunnelSessionType"
}

func (t TunnelSessionType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TunnelSessionValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTunnelSessionValueNull() TunnelSessionValue {
	return TunnelSessionValue{
		state: attr.ValueStateNull,
	}
}

func NewTunnelSessionValueUnknown() TunnelSessionValue {
	return TunnelSessionValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTunnelSessionValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TunnelSessionValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TunnelSessionValue Attribute Value",
				"While creating a TunnelSessionValue value, a missing attribute value was detected. "+
					"A TunnelSessionValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TunnelSessionValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TunnelSessionValue Attribute Type",
				"While creating a TunnelSessionValue value, an invalid attribute value was detected. "+
					"A TunnelSessionValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TunnelSessionValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TunnelSessionValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TunnelSessionValue Attribute Value",
				"While creating a TunnelSessionValue value, an extra attribute value was detected. "+
					"A TunnelSessionValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TunnelSessionValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTunnelSessionValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewTunnelSessionValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewTunnelSessionValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewTunnelSessionValueUnknown(), diags
	}

	return TunnelSessionValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTunnelSessionValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TunnelSessionValue {
	object, diags := NewTunnelSessionValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTunnelSessionValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TunnelSessionType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTunnelSessionValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTunnelSessionValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTunnelSessionValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTunnelSessionValueMust(TunnelSessionValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TunnelSessionType) ValueType(ctx context.Context) attr.Value {
	return TunnelSessionValue{}
}

var _ basetypes.ObjectValuable = TunnelSessionValue{}

type TunnelSessionValue struct {
	Id    basetypes.StringValue `tfsdk:"id"`
	Uri   basetypes.StringValue `tfsdk:"uri"`
	state attr.ValueState
}

func (v TunnelSessionValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TunnelSessionValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TunnelSessionValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TunnelSessionValue) String() string {
	return "TunnelSessionValue"
}

func (v TunnelSessionValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":  v.Id,
			"uri": v.Uri,
		})

	return objVal, diags
}

func (v TunnelSessionValue) Equal(o attr.Value) bool {
	other, ok := o.(TunnelSessionValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v TunnelSessionValue) Type(ctx context.Context) attr.Type {
	return TunnelSessionType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TunnelSessionValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}
}
