// Code generated by apic. DO NOT EDIT.

package ngrok

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/terraform"
)

var (
	resourceAPIKeys_createConfig = `resource "ngrok_api_key" "example" {
  description = "ad-hoc dev testing"
  metadata = "{\"environment\":\"dev\"}"
}`
	resourceAPIKeys_updateConfig = `resource "ngrok_api_key" "example" {
  metadata = "{\"environment\":\"dev\", \"owner_id\": 123}"
}`
)

func TestAccResourceAPIKeys(t *testing.T) {

	resource.Test(t, resource.TestCase{
		Providers:    testAccProviders,
		PreCheck:     func() { testAccPreCheck(t) },
		CheckDestroy: testAccCheckDestroyAPIKeys,
		Steps: []resource.TestStep{
			{
				Config: resourceAPIKeys_createConfig,
				// Check: resource.ComposeAggregateTestCheckFunc(
				// 	testAccCheckCreateAPIKeys,
				// ),
			},
		},
	})
}

func testAccCheckDestroyAPIKeys(s *terraform.State) (err error) {
	return err
}

func testAccCheckCreateAPIKeys(s *terraform.State) (err error) {
	fmt.Sprintf("state=%#v", s)
	return err
}
