// Code generated by apic. DO NOT EDIT.

package ngrok

import (
	"context"
	"fmt"
	"log"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	restapi "github.com/ngrok/terraform-provider-ngrok/restapi"
)

var (
	resourceIPWhitelist_createConfig = `resource "ngrok_ip_whitelist_entry" "example" {
  description = "outbound proxy servers"
  ip_net = "10.1.1.0/24"
}`
	resourceIPWhitelist_updateConfig = `resource "ngrok_ip_whitelist_entry" "example" {
  description = "home office for alan"
  metadata = "{\"type\": \"home office\", \"employee_name\": \"alan\"}"
}`
)

func init() {
	resource.AddTestSweepers("ip_whitelist", &resource.Sweeper{
		Name: "ip_whitelist",
		F: func(region string) error {
			ctx := context.Background()
			client, err := sharedClientForRegion(region)
			if err != nil {
				return fmt.Errorf("Error getting client: %s", err)
			}
			conn := client.(*restapi.Client)

			list, _, err := conn.IPWhitelistList(ctx, nil)
			if err != nil {
				return fmt.Errorf("Error getting list of items: %s", err)
			}
			for _, item := range list.Whitelist {
				// Assume items with empty Description and Metadata are system defined (i.e. API Keys)
				if item.Description != "" && item.Metadata != "" {
					_, _, err := conn.IPWhitelistDelete(ctx, &restapi.Item{ID: item.ID})

					if err != nil {
						log.Printf("Error destroying id %s during sweep: %s", item.ID, err)
					}
				}
			}
			return nil
		},
	})
}

func TestAccResourceIPWhitelist(t *testing.T) {

	resource.Test(t, resource.TestCase{
		Providers:    testAccProviders,
		PreCheck:     func() { testAccPreCheck(t) },
		CheckDestroy: testAccCheckDestroyIPWhitelist,
		Steps: []resource.TestStep{
			{
				Config: resourceIPWhitelist_createConfig,
				// Check: resource.ComposeAggregateTestCheckFunc(
				// 	testAccCheckCreateIPWhitelist,
				// ),
			},
		},
	})
}

func testAccCheckDestroyIPWhitelist(s *terraform.State) (err error) {
	return err
}

func testAccCheckCreateIPWhitelist(s *terraform.State) (err error) {
	fmt.Sprintf("state=%#v", s)
	return err
}
