// Code generated by apic. DO NOT EDIT.

package ngrok

import (
	"context"
	"fmt"
	"log"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/terraform"
	restapi "github.com/ngrok/terraform-provider-ngrok/restapi"
)

var (
	resourceLogDestinations_createConfig = `resource "ngrok_log_destination" "example" {
  description = "kinesis dev stream"
  format = "json"
  metadata = "{\"environment\":\"dev\"}"
  target {
    kinesis {
      auth {
        creds {
          aws_access_key_id = "AKIAIOSFODNN7EXAMPLE"
          aws_secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        }
      }
      stream_arn = "arn:aws:kinesis:us-east-2:123456789012:stream/mystream2"
    }
  }
}`
	resourceLogDestinations_updateConfig = `resource "ngrok_log_destination" "example" {
  description = "kinesis dev stream 1 of 3"
  metadata = "{\"environment\":\"dev\", \"stream\":1}"
}`
)

func init() {
	resource.AddTestSweepers("log_destinations", &resource.Sweeper{
		Name: "log_destinations",
		F: func(region string) error {
			ctx := context.Background()
			client, err := sharedClientForRegion(region)
			if err != nil {
				return fmt.Errorf("Error getting client: %s", err)
			}
			conn := client.(*restapi.Client)

			list, _, err := conn.LogDestinationsList(ctx, nil)
			if err != nil {
				return fmt.Errorf("Error getting list of items: %s", err)
			}
			for _, item := range list.LogDestinations {
				// Assume items with empty Description and Metadata are system defined (i.e. API Keys)
				if item.Description != "" && item.Metadata != "" {
					_, _, err := conn.LogDestinationsDelete(ctx, &restapi.Item{ID: item.ID})

					if err != nil {
						log.Printf("Error destroying id %s during sweep: %s", item.ID, err)
					}
				}
			}
			return nil
		},
	})
}

func TestAccResourceLogDestinations(t *testing.T) {
	t.Skip("Test skipped. See: https://github.com/ngrok-private/ngrok/issues/4723")
	resource.Test(t, resource.TestCase{
		Providers:    testAccProviders,
		PreCheck:     func() { testAccPreCheck(t) },
		CheckDestroy: testAccCheckDestroyLogDestinations,
		Steps: []resource.TestStep{
			{
				Config: resourceLogDestinations_createConfig,
				// Check: resource.ComposeAggregateTestCheckFunc(
				// 	testAccCheckCreateLogDestinations,
				// ),
			},
		},
	})
}

func testAccCheckDestroyLogDestinations(s *terraform.State) (err error) {
	return err
}

func testAccCheckCreateLogDestinations(s *terraform.State) (err error) {
	fmt.Sprintf("state=%#v", s)
	return err
}
