// Code generated by apic. DO NOT EDIT.

package ngrok

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/terraform"
)

var (
	resourceSSHCertificateAuthorities_createConfig = `resource "ngrok_ssh_certificate_authority" "example" {
  description = "Staging Environment Hosts"
  private_key_type = "ed25519"
}`
	resourceSSHCertificateAuthorities_updateConfig = `resource "ngrok_ssh_certificate_authority" "example" {
  metadata = "{\"region\": \"us-east-1\"}"
}`
)

func TestAccResourceSSHCertificateAuthorities(t *testing.T) {

	resource.Test(t, resource.TestCase{
		Providers:    testAccProviders,
		PreCheck:     func() { testAccPreCheck(t) },
		CheckDestroy: testAccCheckDestroySSHCertificateAuthorities,
		Steps: []resource.TestStep{
			{
				Config: resourceSSHCertificateAuthorities_createConfig,
				// Check: resource.ComposeAggregateTestCheckFunc(
				// 	testAccCheckCreateSSHCertificateAuthorities,
				// ),
			},
		},
	})
}

func testAccCheckDestroySSHCertificateAuthorities(s *terraform.State) (err error) {
	return err
}

func testAccCheckCreateSSHCertificateAuthorities(s *terraform.State) (err error) {
	fmt.Sprintf("state=%#v", s)
	return err
}
