// Code generated by apic. DO NOT EDIT.

package ngrok

import (
	"context"
	"log"
	"net/http"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	restapi "github.com/ngrok/terraform-provider-ngrok/restapi"
)

func resourceIPPolicyRules() *schema.Resource {
	return &schema.Resource{
		Create: resourceIPPolicyRulesCreate,
		Read:   resourceIPPolicyRulesGet,
		Update: resourceIPPolicyRulesUpdate,
		Delete: resourceIPPolicyRulesDelete,

		Schema: map[string]*schema.Schema{
			"cidr": {
				Type:        schema.TypeString,
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ForceNew:    false,
				Description: "an IP or IP range specified in CIDR notation. IPv4 and IPv6 are both supported.",
			},
			"created_at": {
				Type:        schema.TypeString,
				Required:    false,
				Computed:    true,
				Optional:    true,
				Sensitive:   false,
				ForceNew:    true,
				Description: "timestamp when the IP policy rule was created, RFC 3339 format",
			},
			"description": {
				Type:        schema.TypeString,
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ForceNew:    false,
				Description: "human-readable description of the source IPs of this IP rule. optional, max 255 bytes.",
			},
			"ip_policy": {
				Type:        schema.TypeSet,
				Required:    false,
				Computed:    true,
				Optional:    true,
				Sensitive:   false,
				ForceNew:    true,
				Description: "object describing the IP policy this IP Policy Rule belongs to",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"ngrok_id": {
							Type:        schema.TypeString,
							Required:    false,
							Computed:    true,
							Optional:    true,
							Sensitive:   false,
							ForceNew:    false,
							Description: "a resource identifier",
						},
						"uri": {
							Type:        schema.TypeString,
							Required:    false,
							Computed:    true,
							Optional:    true,
							Sensitive:   false,
							ForceNew:    true,
							Description: "a uri for locating a resource",
						},
					},
				},
			},
			"ip_policy_id": {
				Type:        schema.TypeString,
				Required:    true,
				Computed:    false,
				Optional:    false,
				Sensitive:   false,
				ForceNew:    true,
				Description: "ID of the IP policy this IP policy rule will be attached to",
			},
			"metadata": {
				Type:        schema.TypeString,
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ForceNew:    false,
				Description: "arbitrary user-defined machine-readable data of this IP policy rule. optional, max 4096 bytes.",
			},
			"ngrok_id": {
				Type:        schema.TypeString,
				Required:    false,
				Computed:    true,
				Optional:    true,
				Sensitive:   false,
				ForceNew:    false,
				Description: "unique identifier for this IP policy rule",
			},
			"uri": {
				Type:        schema.TypeString,
				Required:    false,
				Computed:    true,
				Optional:    true,
				Sensitive:   false,
				ForceNew:    true,
				Description: "URI of the IP policy rule API resource",
			},
		},
	}
}

func resourceIPPolicyRulesCreate(d *schema.ResourceData, m interface{}) (err error) {
	b := m.(*base)

	var arg restapi.IPPolicyRuleCreate
	if v, ok := d.GetOk("description"); ok {
		arg.Description = *expandString(v)
	}
	if v, ok := d.GetOk("metadata"); ok {
		arg.Metadata = *expandString(v)
	}
	if v, ok := d.GetOk("cidr"); ok {
		arg.CIDR = *expandString(v)
	}
	if v, ok := d.GetOk("ip_policy_id"); ok {
		arg.IPPolicyID = *expandString(v)
	}

	res, _, err := b.client.IPPolicyRulesCreate(context.Background(), &arg)
	if err != nil {
		log.Printf("[ERROR] IPPolicyRulesCreate: %s", err)
		return err
	}
	d.SetId(res.ID)

	return resourceIPPolicyRulesGet(d, m)
}

func resourceIPPolicyRulesGet(d *schema.ResourceData, m interface{}) (err error) {
	b := m.(*base)

	res, resp, err := b.client.IPPolicyRulesGet(context.Background(), &restapi.Item{
		ID: d.Id(),
	})
	return resourceIPPolicyRulesGetDecode(d, res, resp, err)
}

func resourceIPPolicyRulesGetDecode(d *schema.ResourceData, res *restapi.IPPolicyRule, resp *http.Response, err error) error {
	switch {
	case resp != nil && resp.StatusCode == 404:
		d.SetId("")
	case err != nil:
		log.Printf("[ERROR] IPPolicyRulesGet: %s", err)
		return err
	default:
		d.Set("cidr", res.CIDR)
		d.Set("created_at", res.CreatedAt)
		d.Set("description", res.Description)
		d.Set("ip_policy", flattenRef(&res.IPPolicy))
		d.Set("ip_policy_id", res.IPPolicy.ID)
		d.Set("metadata", res.Metadata)
		d.Set("ngrok_id", res.ID)
		d.Set("uri", res.URI)
	}
	return nil
}

func resourceIPPolicyRulesUpdate(d *schema.ResourceData, m interface{}) (err error) {
	b := m.(*base)

	var arg restapi.IPPolicyRuleUpdate
	arg.ID = d.Id()
	if v, ok := d.GetOk("ngrok_id"); ok {
		arg.ID = *expandString(v)
	}
	if v, ok := d.GetOk("description"); ok {
		arg.Description = expandString(v)
	}
	if v, ok := d.GetOk("metadata"); ok {
		arg.Metadata = expandString(v)
	}
	if v, ok := d.GetOk("cidr"); ok {
		arg.CIDR = expandString(v)
	}

	res, _, err := b.client.IPPolicyRulesUpdate(context.Background(), &arg)
	if err != nil {
		log.Printf("[ERROR] IPPolicyRulesUpdate: %s", err)
		return err
	}
	d.SetId(res.ID)

	return resourceIPPolicyRulesGet(d, m)
}

func resourceIPPolicyRulesDelete(d *schema.ResourceData, m interface{}) (err error) {
	b := m.(*base)
	_, _, err = b.client.IPPolicyRulesDelete(context.Background(), &restapi.Item{ID: d.Id()})
	if err != nil {
		log.Printf("[ERROR] IPPolicyRulesDelete: %s", err)
	}
	return err
}
