// Code generated by apic. DO NOT EDIT.

package ngrok

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/terraform"
)

var (
	resourceIPWhitelist_createConfig = `resource "ngrok_ip_whitelist_entry" "example" {
  description = "outbound proxy servers"
  ip_net = "10.1.1.0/24"
}`
	resourceIPWhitelist_updateConfig = `resource "ngrok_ip_whitelist_entry" "example" {
  description = "home office for alan"
  metadata = "{\"type\": \"home office\", \"employee_name\": \"alan\"}"
}`
)

func TestAccResourceIPWhitelist(t *testing.T) {

	resource.Test(t, resource.TestCase{
		Providers:    testAccProviders,
		PreCheck:     func() { testAccPreCheck(t) },
		CheckDestroy: testAccCheckDestroyIPWhitelist,
		Steps: []resource.TestStep{
			{
				Config: resourceIPWhitelist_createConfig,
				// Check: resource.ComposeAggregateTestCheckFunc(
				// 	testAccCheckCreateIPWhitelist,
				// ),
			},
		},
	})
}

func testAccCheckDestroyIPWhitelist(s *terraform.State) (err error) {
	return err
}

func testAccCheckCreateIPWhitelist(s *terraform.State) (err error) {
	fmt.Sprintf("state=%#v", s)
	return err
}
