// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_reserved_addr

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ReservedAddrResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"addr": schema.StringAttribute{
				Computed:            true,
				Description:         "hostname:port of the reserved address that was assigned at creation time\n",
				MarkdownDescription: "hostname:port of the reserved address that was assigned at creation time\n",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the reserved address was created, RFC 3339 format\n",
				MarkdownDescription: "timestamp when the reserved address was created, RFC 3339 format\n",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "human-readable description of what this reserved address will be used for\n",
				MarkdownDescription: "human-readable description of what this reserved address will be used for\n",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "unique reserved address resource identifier\n",
				MarkdownDescription: "unique reserved address resource identifier\n",
			},
			"metadata": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "arbitrary user-defined machine-readable data of this reserved address. Optional, max 4096 bytes.\n",
				MarkdownDescription: "arbitrary user-defined machine-readable data of this reserved address. Optional, max 4096 bytes.\n",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "reserve the address in this geographic ngrok datacenter. Optional, default is us. (au, eu, ap, us, jp, in, sa)\n",
				MarkdownDescription: "reserve the address in this geographic ngrok datacenter. Optional, default is us. (au, eu, ap, us, jp, in, sa)\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI of the reserved address API resource\n",
				MarkdownDescription: "URI of the reserved address API resource\n",
			},
		},
	}
}

type ReservedAddrModel struct {
	Addr        types.String `tfsdk:"addr"`
	CreatedAt   types.String `tfsdk:"created_at"`
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Metadata    types.String `tfsdk:"metadata"`
	Region      types.String `tfsdk:"region"`
	Uri         types.String `tfsdk:"uri"`
}
