// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_ssh_host_certificate

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SshHostCertificateDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"certificate": schema.StringAttribute{
				Computed:            true,
				Description:         "the signed SSH certificate in OpenSSH Authorized Keys format. this value should be placed in a `-cert.pub` certificate file on disk that should be referenced in your `sshd_config` configuration file with a `HostCertificate` directive\n",
				MarkdownDescription: "the signed SSH certificate in OpenSSH Authorized Keys format. this value should be placed in a `-cert.pub` certificate file on disk that should be referenced in your `sshd_config` configuration file with a `HostCertificate` directive\n",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the SSH Host Certificate API resource was created, RFC 3339 format\n",
				MarkdownDescription: "timestamp when the SSH Host Certificate API resource was created, RFC 3339 format\n",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "human-readable description of this SSH Host Certificate. optional, max 255 bytes.\n",
				MarkdownDescription: "human-readable description of this SSH Host Certificate. optional, max 255 bytes.\n",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "a resource identifier\n",
				MarkdownDescription: "a resource identifier\n",
			},
			"key_type": schema.StringAttribute{
				Computed:            true,
				Description:         "the key type of the `public_key`, one of `rsa`, `ecdsa` or `ed25519`\n",
				MarkdownDescription: "the key type of the `public_key`, one of `rsa`, `ecdsa` or `ed25519`\n",
			},
			"metadata": schema.StringAttribute{
				Computed:            true,
				Description:         "arbitrary user-defined machine-readable data of this SSH Host Certificate. optional, max 4096 bytes.\n",
				MarkdownDescription: "arbitrary user-defined machine-readable data of this SSH Host Certificate. optional, max 4096 bytes.\n",
			},
			"principals": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "the list of principals included in the ssh host certificate. This is the list of hostnames and/or IP addresses that are authorized to serve SSH traffic with this certificate. Dangerously, if no principals are specified, this certificate is considered valid for all hosts.\n",
				MarkdownDescription: "the list of principals included in the ssh host certificate. This is the list of hostnames and/or IP addresses that are authorized to serve SSH traffic with this certificate. Dangerously, if no principals are specified, this certificate is considered valid for all hosts.\n",
			},
			"public_key": schema.StringAttribute{
				Computed:            true,
				Description:         "a public key in OpenSSH Authorized Keys format that this certificate signs\n",
				MarkdownDescription: "a public key in OpenSSH Authorized Keys format that this certificate signs\n",
			},
			"ssh_certificate_authority_id": schema.StringAttribute{
				Computed:            true,
				Description:         "the ssh certificate authority that is used to sign this ssh host certificate\n",
				MarkdownDescription: "the ssh certificate authority that is used to sign this ssh host certificate\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI of the SSH Host Certificate API resource\n",
				MarkdownDescription: "URI of the SSH Host Certificate API resource\n",
			},
			"valid_after": schema.StringAttribute{
				Computed:            true,
				Description:         "the time when the ssh host certificate becomes valid, in RFC 3339 format.\n",
				MarkdownDescription: "the time when the ssh host certificate becomes valid, in RFC 3339 format.\n",
			},
			"valid_until": schema.StringAttribute{
				Computed:            true,
				Description:         "the time after which the ssh host certificate becomes invalid, in RFC 3339 format. the OpenSSH certificates RFC calls this `valid_before`.\n",
				MarkdownDescription: "the time after which the ssh host certificate becomes invalid, in RFC 3339 format. the OpenSSH certificates RFC calls this `valid_before`.\n",
			},
		},
	}
}

type SshHostCertificateModel struct {
	Certificate               types.String `tfsdk:"certificate"`
	CreatedAt                 types.String `tfsdk:"created_at"`
	Description               types.String `tfsdk:"description"`
	Id                        types.String `tfsdk:"id"`
	KeyType                   types.String `tfsdk:"key_type"`
	Metadata                  types.String `tfsdk:"metadata"`
	Principals                types.List   `tfsdk:"principals"`
	PublicKey                 types.String `tfsdk:"public_key"`
	SshCertificateAuthorityId types.String `tfsdk:"ssh_certificate_authority_id"`
	Uri                       types.String `tfsdk:"uri"`
	ValidAfter                types.String `tfsdk:"valid_after"`
	ValidUntil                types.String `tfsdk:"valid_until"`
}
