// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_service_user

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ServiceUserResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"active": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "whether or not the service is active\n",
				MarkdownDescription: "whether or not the service is active\n",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the api key was created, RFC 3339 format\n",
				MarkdownDescription: "timestamp when the api key was created, RFC 3339 format\n",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "unique API key resource identifier\n",
				MarkdownDescription: "unique API key resource identifier\n",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "human-readable name used to identify the service\n",
				MarkdownDescription: "human-readable name used to identify the service\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI to the API resource of this service user\n",
				MarkdownDescription: "URI to the API resource of this service user\n",
			},
		},
	}
}

type ServiceUserModel struct {
	Active    types.Bool   `tfsdk:"active"`
	CreatedAt types.String `tfsdk:"created_at"`
	Id        types.String `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
	Uri       types.String `tfsdk:"uri"`
}
