// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_ip_policy

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func IpPolicyDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the IP policy was created, RFC 3339 format\n",
				MarkdownDescription: "timestamp when the IP policy was created, RFC 3339 format\n",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "human-readable description of the source IPs of this IP policy. optional, max 255 bytes.\n",
				MarkdownDescription: "human-readable description of the source IPs of this IP policy. optional, max 255 bytes.\n",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "a resource identifier\n",
				MarkdownDescription: "a resource identifier\n",
			},
			"metadata": schema.StringAttribute{
				Computed:            true,
				Description:         "arbitrary user-defined machine-readable data of this IP policy. optional, max 4096 bytes.\n",
				MarkdownDescription: "arbitrary user-defined machine-readable data of this IP policy. optional, max 4096 bytes.\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI of the IP Policy API resource\n",
				MarkdownDescription: "URI of the IP Policy API resource\n",
			},
		},
	}
}

type IpPolicyModel struct {
	CreatedAt   types.String `tfsdk:"created_at"`
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Metadata    types.String `tfsdk:"metadata"`
	Uri         types.String `tfsdk:"uri"`
}
