// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_ip_restriction

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func IpRestrictionResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "timestamp when the IP restriction was created, RFC 3339 format\n",
				MarkdownDescription: "timestamp when the IP restriction was created, RFC 3339 format\n",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "human-readable description of this IP restriction. optional, max 255 bytes.\n",
				MarkdownDescription: "human-readable description of this IP restriction. optional, max 255 bytes.\n",
			},
			"enforced": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "true if the IP restriction will be enforced. if false, only warnings will be issued\n",
				MarkdownDescription: "true if the IP restriction will be enforced. if false, only warnings will be issued\n",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "unique identifier for this IP restriction\n",
				MarkdownDescription: "unique identifier for this IP restriction\n",
			},
			"ip_policies": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "a resource identifier\n",
							MarkdownDescription: "a resource identifier\n",
						},
						"uri": schema.StringAttribute{
							Computed:            true,
							Description:         "a uri for locating a resource\n",
							MarkdownDescription: "a uri for locating a resource\n",
						},
					},
					CustomType: IpPoliciesType{
						ObjectType: types.ObjectType{
							AttrTypes: IpPoliciesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "the set of IP policies that are used to enforce the restriction\n",
				MarkdownDescription: "the set of IP policies that are used to enforce the restriction\n",
			},
			"ip_policy_ids": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "the set of IP policy identifiers that are used to enforce the restriction\n",
				MarkdownDescription: "the set of IP policy identifiers that are used to enforce the restriction\n",
			},
			"metadata": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "arbitrary user-defined machine-readable data of this IP restriction. optional, max 4096 bytes.\n",
				MarkdownDescription: "arbitrary user-defined machine-readable data of this IP restriction. optional, max 4096 bytes.\n",
			},
			"type": schema.StringAttribute{
				Required:            true,
				Description:         "the type of IP restriction. this defines what traffic will be restricted with the attached policies. four values are currently supported: `dashboard`, `api`, `agent`, and `endpoints`\n",
				MarkdownDescription: "the type of IP restriction. this defines what traffic will be restricted with the attached policies. four values are currently supported: `dashboard`, `api`, `agent`, and `endpoints`\n",
			},
			"uri": schema.StringAttribute{
				Computed:            true,
				Description:         "URI of the IP restriction API resource\n",
				MarkdownDescription: "URI of the IP restriction API resource\n",
			},
		},
	}
}

type IpRestrictionModel struct {
	CreatedAt   types.String `tfsdk:"created_at"`
	Description types.String `tfsdk:"description"`
	Enforced    types.Bool   `tfsdk:"enforced"`
	Id          types.String `tfsdk:"id"`
	IpPolicies  types.List   `tfsdk:"ip_policies"`
	IpPolicyIds types.List   `tfsdk:"ip_policy_ids"`
	Metadata    types.String `tfsdk:"metadata"`
	Type        types.String `tfsdk:"type"`
	Uri         types.String `tfsdk:"uri"`
}

var _ basetypes.ObjectTypable = IpPoliciesType{}

type IpPoliciesType struct {
	basetypes.ObjectType
}

func (t IpPoliciesType) Equal(o attr.Type) bool {
	other, ok := o.(IpPoliciesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t IpPoliciesType) String() string {
	return "IpPoliciesType"
}

func (t IpPoliciesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return IpPoliciesValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewIpPoliciesValueNull() IpPoliciesValue {
	return IpPoliciesValue{
		state: attr.ValueStateNull,
	}
}

func NewIpPoliciesValueUnknown() IpPoliciesValue {
	return IpPoliciesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIpPoliciesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (IpPoliciesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing IpPoliciesValue Attribute Value",
				"While creating a IpPoliciesValue value, a missing attribute value was detected. "+
					"A IpPoliciesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IpPoliciesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid IpPoliciesValue Attribute Type",
				"While creating a IpPoliciesValue value, an invalid attribute value was detected. "+
					"A IpPoliciesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IpPoliciesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("IpPoliciesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra IpPoliciesValue Attribute Value",
				"While creating a IpPoliciesValue value, an extra attribute value was detected. "+
					"A IpPoliciesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra IpPoliciesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIpPoliciesValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewIpPoliciesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewIpPoliciesValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewIpPoliciesValueUnknown(), diags
	}

	return IpPoliciesValue{
		Id:    idVal,
		Uri:   uriVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewIpPoliciesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) IpPoliciesValue {
	object, diags := NewIpPoliciesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIpPoliciesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t IpPoliciesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIpPoliciesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIpPoliciesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIpPoliciesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIpPoliciesValueMust(IpPoliciesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t IpPoliciesType) ValueType(ctx context.Context) attr.Value {
	return IpPoliciesValue{}
}

var _ basetypes.ObjectValuable = IpPoliciesValue{}

type IpPoliciesValue struct {
	Id    basetypes.StringValue `tfsdk:"id"`
	Uri   basetypes.StringValue `tfsdk:"uri"`
	state attr.ValueState
}

func (v IpPoliciesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v IpPoliciesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v IpPoliciesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v IpPoliciesValue) String() string {
	return "IpPoliciesValue"
}

func (v IpPoliciesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":  v.Id,
			"uri": v.Uri,
		})

	return objVal, diags
}

func (v IpPoliciesValue) Equal(o attr.Value) bool {
	other, ok := o.(IpPoliciesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v IpPoliciesValue) Type(ctx context.Context) attr.Type {
	return IpPoliciesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v IpPoliciesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":  basetypes.StringType{},
		"uri": basetypes.StringType{},
	}
}
